# Generated by Django 3.1.7 on 2021-06-17 22:16

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='ZInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=120)),
                ('hash', django.contrib.postgres.fields.hstore.HStoreField()),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
