# Generated by Django 3.1.7 on 2021-06-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zinfo',
            name='percent',
            field=models.CharField(default='50%', max_length=10),
            preserve_default=False,
        ),
    ]
