# Generated by Django 3.1.7 on 2021-06-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_zinfo_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='zinfo',
            name='language',
            field=models.CharField(default='en', max_length=3),
            preserve_default=False,
        ),
    ]
