# Generated by Django 3.1.7 on 2021-06-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_zinfo_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zinfo',
            name='language',
            field=models.CharField(max_length=10),
        ),
    ]
